language: node_js

node_js:
  - "stable"

sudo: false

cache:
  npm: true
  directories:
    - node_modules

# so as to ensure slick-carousel is always there
before_script:
  - npm install -g gulp-cli
  - npm install slick-carousel

script:
  - npm run build
  - npm run test

notifications:
  email:
    on_failure: always
    on_success: always